### Generate Account Statement
POST http://localhost:8000/api/v1/statements
Content-Type: application/json
Accept: application/json
X-API-KEY: arkagenledger4321

{
    "account_number": "11101007",
    "start_date": "2025-04-01",
    "end_date": "2025-04-30", 
    "project_code0": "023C"
}

### Test the statements GET test route
GET http://localhost:8000/api/v1/statements-test
Accept: application/json
X-API-KEY: arkagenledger4321

### Test the debug route
GET http://localhost:8000/api/debug
Accept: application/json
X-API-KEY: arkagenledger4321

### Test the statements debug route
POST http://localhost:8000/api/v1/statements-debug
Content-Type: application/json
Accept: application/json
X-API-KEY: arkagenledger4321

{
    "account_number": "11101001",
    "start_date": "2025-01-01",
    "end_date": "2025-04-30"
}

###
GET http://localhost:8000/test-route

###
GET http://localhost:8000/api/test

###
GET http://localhost:8000/api/debug


